version: 2
jobs:
  build:
    docker:
      - image: gcc:latest
      - image: postgres:9.6
        name: postgres
    steps:
      - checkout
      - run: gcc -o binary_search binary_search.cpp
      - run: sleep 60
