version: 2
jobs:
  compile:
    docker:
      - image: frolvlad/alpine-gcc:latest
    steps:
      - checkout
      - run: g++ -o binary_search binary_search.cpp
  echo:
    docker:
      - image: ubuntu:latest
    steps:
      - run: echo "hi there"

workflows:
  version: 2
  compile-and-echo:
    jobs:
      - compile
      - echo
